# Generated by Django 4.0.1 on 2022-09-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Ordered', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurent',
            name='type',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.customers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Restaurent_s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res', to='food.restaurent'),
        ),
    ]
