# Generated by Django 4.0.1 on 2022-09-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_orders_status_restaurent_type_alter_orders_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='userId',
            new_name='userId_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
