# Generated by Django 4.0.1 on 2022-09-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_userid_orders_userid_id_remove_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='userId_id',
            new_name='userId',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Ordered', max_length=30),
        ),
    ]
