# Generated by Django 4.0.1 on 2022-09-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_userid_id_orders_userid_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='userId',
        ),
        migrations.AddField(
            model_name='orders',
            name='userId_id',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
