# Generated by Django 4.1.1 on 2022-09-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_product_unique_restaurent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unique_restaurent_id',
            new_name='unique_product_id',
        ),
        migrations.RenameField(
            model_name='restaurent',
            old_name='unique_product_id',
            new_name='unique_restaurent_id',
        ),
    ]
