# Generated by Django 4.1.1 on 2022-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_orders_payment_status_orders_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orginal_price',
            field=models.IntegerField(default=0),
        ),
    ]
