# Generated by Django 4.1.1 on 2022-10-31 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_product_orginal_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
