# Generated by Django 4.1.1 on 2022-10-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='area',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
